version: '3.8'

services:
  db:
    build: ./database
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      mynet:
        ipv4_address: 172.21.0.10

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5001:5000"
    networks:
      mynet:
        ipv4_address: 172.21.0.20

volumes:
  pgdata:

networks:
  mynet:
    external: true